name: "git-restore-mtime"
description: "Restore file's modified time (timestamp) based on git commits"
author: "Pixelcop Research, Inc."
inputs:
  working-directory:
    description: "Where to run the action"
    required: false
    default: "."
  args:
    description: "Command line arguments to pass to git-restore-mtime"
    required: false
    default: ""
branding:
  icon: "clock"
  color: "orange"
runs:
  using: "composite"
  steps:
    - shell: bash
      if: runner.os != 'Windows'
      run: |
        cd "${{ inputs.working-directory }}" && python3 "$GITHUB_ACTION_PATH"/git-restore-mtime ${{ inputs.args }}
    - shell: pwsh
      if: runner.os == 'Windows'
      run: |
        $PythonDir = "$env:RUNNER_TEMP\embeddable-python"
        if (!(Test-Path "$PythonDir\python.exe")) {
          $PythonUrl = "https://www.python.org/ftp/python/3.12.7/python-3.12.7-embed-amd64.zip"
          $ZipPath = "$env:RUNNER_TEMP\python-embed.zip"
          Invoke-WebRequest -Uri $PythonUrl -OutFile $ZipPath
          Expand-Archive -Path $ZipPath -DestinationPath $PythonDir -Force
          Remove-Item $ZipPath
        }
        cd "${{ inputs.working-directory }}"
        & "$PythonDir\python.exe" "$env:GITHUB_ACTION_PATH\git-restore-mtime" ${{ inputs.args }}
